export const SYSTEMCONFIG_ERROR_NOT_FOUND = "System config item not found!";

export const SYSTEMCONFIG_KEY = {
  DRIVER_TRIP_FARE_SERVICE_CHARGE_PERCENTAGE:
    "DRIVER_TRIP_FARE_SERVICE_CHARGE_PERCENTAGE",
};
